# Generated by Django 3.0.2 on 2020-08-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('mg', models.CharField(max_length=200)),
                ('tablets', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('s_pack', models.IntegerField(default=0)),
                ('s_tablet', models.IntegerField(default=0)),
                ('stock_pack', models.IntegerField(default=0)),
                ('stock_tablet', models.IntegerField(default=0)),
                ('purchase_pack', models.IntegerField(default=0)),
                ('purchase_tablet', models.IntegerField(default=0)),
                ('purchase_return_pack', models.IntegerField(default=0)),
                ('purchase_return_tablet', models.IntegerField(default=0)),
                ('sale_pack', models.IntegerField(default=0)),
                ('sale_tablet', models.IntegerField(default=0)),
                ('sale_return_pack', models.IntegerField(default=0)),
                ('sale_return_tablet', models.IntegerField(default=0)),
                ('used_pack', models.IntegerField(default=0)),
                ('used_tablet', models.IntegerField(default=0)),
                ('active', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], default='0', max_length=1)),
                ('type_id', models.CharField(choices=[('T', 'Tablet'), ('S', 'Syrup'), ('I', 'Injection'), ('C', 'Common')], default='T', max_length=1)),
                ('initial_balance', models.IntegerField(blank=True, null=True)),
                ('initial_balance_db', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('created_date', models.DateTimeField(verbose_name='date')),
                ('ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Supplier')),
            ],
        ),
    ]
