# Generated by Django 3.0.2 on 2020-08-04 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('dr_total', models.IntegerField(default=0)),
                ('cr_total', models.IntegerField(default=0)),
                ('remaining', models.IntegerField(default=0)),
                ('returns', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('balance_dc', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('Ledger_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger_Type')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Entry_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('pack', models.IntegerField(default=0)),
                ('tablet', models.IntegerField(default=0)),
                ('batch_no', models.CharField(max_length=200)),
                ('c_price', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('tax', models.IntegerField(default=0)),
                ('discount_per', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('total_amount', models.IntegerField(default=0)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('dc', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], default='D', max_length=1)),
                ('narration', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('active_product', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('F', 'Finished')], default='I', max_length=1)),
                ('sale_price', models.IntegerField(blank=True, default=0, null=True)),
                ('tpacks', models.IntegerField(default=0)),
                ('rpack', models.IntegerField(default=0)),
                ('rtablet', models.IntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Entry')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Entry_Type'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger'),
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Ledger')),
            ],
        ),
    ]
